using System;
using Tools;

namespace Tools
{
    public static class HondaTestData
    {
        public static Vehicle HondaOdyssee()
        {
            var honda = new Vehicle
                            {
                                Make = "Honda",
                                Model = "Odyssee",
                                Year = 2005,
                                OdometerUnit = UnitOfMeasure.Distance.Mile,
                                Label = "'05 odyssee"
                            };

            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("9/28/2005"), FillAmount = 14.136, PricePerUnit = 2.759, OdometerReading = 1008, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("9/30/2005"), FillAmount = 17.513, PricePerUnit = 2.999, OdometerReading = 1385 , OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("9/30/2005").AddMilliseconds(5000), FillAmount = 7, PricePerUnit = 2.999, OdometerReading = 1548 , OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/16/2005"), FillAmount = 11.62, PricePerUnit = 2.659, OdometerReading = 1780 , OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/5/2005"), FillAmount = 15.002, PricePerUnit = 2.399, OdometerReading = 2127 , OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/7/2005"), FillAmount = 16.334, PricePerUnit = 2.199, OdometerReading = 2519, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/9/2005"), FillAmount = 11.589, PricePerUnit = 2.389, OdometerReading = 2755, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/17/2005"), FillAmount = 13.684, PricePerUnit = 2.229, OdometerReading = 3009, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/29/2005"), FillAmount = 17.254, PricePerUnit = 2.199, OdometerReading = 3336, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/31/2005"), FillAmount = 18.18, PricePerUnit = 2.299, OdometerReading = 3644, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/06/2006"), FillAmount = 14.84, PricePerUnit = 2.399, OdometerReading = 3977, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/17/2006"), FillAmount = 10.41, PricePerUnit = 2.359, OdometerReading = 4175, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/24/2006"), FillAmount = 16.575, PricePerUnit = 2.359, OdometerReading = 4534, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/01/2006"), FillAmount = 19.36, PricePerUnit = 2.349, OdometerReading = 4901, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/18/2006"), FillAmount = 13.998, PricePerUnit = 2.299, OdometerReading = 5151, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/19/2006"), FillAmount = 17.649, PricePerUnit = 2.299, OdometerReading = 5525, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/04/2006"), FillAmount = 16.497, PricePerUnit = 2.659, OdometerReading = 5803, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/16/2006"), FillAmount = 19.235, PricePerUnit = 2.799, OdometerReading =  6170, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/22/2006"), FillAmount = 16.47, PricePerUnit = 2.899, OdometerReading = 6553, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/09/2006"), FillAmount = 17.442, PricePerUnit = 2.849, OdometerReading = 6952, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/23/2006"), FillAmount = 15.108, PricePerUnit = 2.859, OdometerReading = 7215, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/07/2006"), FillAmount = 18, PricePerUnit = 2.939, OdometerReading = 7559, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/11/2006"), FillAmount = 18.190, PricePerUnit = 2.959, OdometerReading = 7980, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/09/2006"), FillAmount = 14.838, PricePerUnit = 3.079, OdometerReading =  8317, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/19/2006"), FillAmount = 15.151, PricePerUnit = 3.079, OdometerReading = 8654, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/06/2006"), FillAmount = 17.766, PricePerUnit = 3.299, OdometerReading =  9009, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/06/2006").AddMilliseconds(10), FillAmount = 11.202, PricePerUnit = 3.299, OdometerReading = 9209, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/09/2006"), FillAmount = 13.486, PricePerUnit = 3.149, OdometerReading = 9521, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/12/2006"), FillAmount = 18.326, PricePerUnit = 3.139, OdometerReading =  9855, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/16/2006"), FillAmount = 8.584, PricePerUnit = 3.129, OdometerReading = 10000, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("09/08/2006"), FillAmount = 17.724, PricePerUnit = 2.699, OdometerReading =  10391, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("09/19/2006"), FillAmount = 18.003, PricePerUnit = 2.479, OdometerReading = 10714, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("09/29/2006"), FillAmount = 13.803, PricePerUnit = 2.359, OdometerReading = 11013, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/01/2006"), FillAmount = 15.663, PricePerUnit = 2.329, OdometerReading =  11385, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/08/2006"), FillAmount = 16.4, PricePerUnit = 2.256, OdometerReading = 11749, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/20/2006"), FillAmount = 16.674, PricePerUnit = 2.259, OdometerReading = 12070, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/4/2006"), FillAmount = 14.084, PricePerUnit = 2.259, OdometerReading = 12325, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/17/2006"), FillAmount = 15.536, PricePerUnit = 2.259, OdometerReading = 12645 , OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/29/2006"), FillAmount = 18.16, PricePerUnit = 2.259, OdometerReading = 12986 , OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/30/2006"), FillAmount = 10.174, PricePerUnit = 2.259, OdometerReading = 13207, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/24/2006"), FillAmount = 16.710, PricePerUnit = 2.359, OdometerReading =  13507, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/01/2007"), FillAmount = 11.230, PricePerUnit = 2.279, OdometerReading = 13708, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/08/2007"), FillAmount = 16.333, PricePerUnit = 2.299, OdometerReading = 14089, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/26/2007"), FillAmount = 14.37, PricePerUnit = 2.159, OdometerReading = 14330, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/11/2007"), FillAmount = 9.228, PricePerUnit = 2.269, OdometerReading = 14486, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/12/2007"), FillAmount = 16.341, PricePerUnit = 2.249, OdometerReading = 14868, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/16/2007"), FillAmount = 17.696, PricePerUnit = 2.499, OdometerReading = 15159, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/07/2007"), FillAmount = 17.863, PricePerUnit = 2.799, OdometerReading = 15499, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/08/2007"), FillAmount = 10.141, PricePerUnit = 2.759, OdometerReading = 15738, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/19/2007"), FillAmount = 17.86, PricePerUnit = 2.799, OdometerReading = 16124, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/11/2007"), FillAmount = 16.411, PricePerUnit = 3.199, OdometerReading = 16438, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/18/2007"), FillAmount = 11.683, PricePerUnit = 3.299, OdometerReading = 16657, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/19/2007"), FillAmount = 8.541, PricePerUnit = 3.399, OdometerReading = 16830, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/14/2007"), FillAmount = 18.643, PricePerUnit = 3.129, OdometerReading = 17270, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/01/2007"), FillAmount = 17.615, PricePerUnit = 3.039, OdometerReading = 17638, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/14/2007"), FillAmount = 17.539, PricePerUnit = 3.199, OdometerReading = 17992, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/23/2007"), FillAmount = 16.787, PricePerUnit = 3.189, OdometerReading = 18290, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/24/2007"), FillAmount = 15.301, PricePerUnit = 3.179, OdometerReading = 18570, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/29/2007"), FillAmount = 18.109, PricePerUnit = 2.969, OdometerReading = 18982, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/31/2007"), FillAmount = 15.178, PricePerUnit = 2.999, OdometerReading = 19236, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/04/2007"), FillAmount = 17, PricePerUnit = 2.999, OdometerReading = 19552, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/11/2007"), FillAmount = 18.285, PricePerUnit = 2.859, OdometerReading = 19861, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/24/2007"), FillAmount = 15.873, PricePerUnit = 3.099, OdometerReading = 20218, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("09/01/2007"), FillAmount = 14.878, PricePerUnit = 3.059, OdometerReading = 20481, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("09/13/2007"), FillAmount = 17.605, PricePerUnit = 2.939, OdometerReading = 20847, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("09/23/2007"), FillAmount = 18.002, PricePerUnit = 2.919, OdometerReading = 21179, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/13/2007"), FillAmount = 18.703, PricePerUnit = 2.969, OdometerReading = 21554, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/09/2007"), FillAmount = 17.896, PricePerUnit = 3.159, OdometerReading = 21866, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/16/2007"), FillAmount = 14, PricePerUnit = 3.219, OdometerReading = 22172, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/09/2007"), FillAmount = 17.978, PricePerUnit = 2.999, OdometerReading = 22499, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/15/2007"), FillAmount = 14.851, PricePerUnit = 2.989, OdometerReading = 22785, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/21/2007"), FillAmount = 14.951, PricePerUnit = 2.979, OdometerReading = 23085, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/29/2007"), FillAmount = 9.775, PricePerUnit = 3.099, OdometerReading = 23242, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/01/2008"), FillAmount = 17.976, PricePerUnit = 3.099, OdometerReading = 23649, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/11/2008"), FillAmount = 15.735, PricePerUnit = 3.099, OdometerReading = 23952, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/12/2008"), FillAmount = 16.674, PricePerUnit = 2.999, OdometerReading = 24324, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/12/2008").AddMilliseconds(20), FillAmount = 16.286, PricePerUnit = 3.099, OdometerReading = 24669, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/13/2008"), FillAmount = 12.096, PricePerUnit = 2.959, OdometerReading = 24997, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/17/2008"), FillAmount = 17.972, PricePerUnit = 2.949, OdometerReading = 25356, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/17/2008").AddMilliseconds(20), FillAmount = 17.246, PricePerUnit = 2.899, OdometerReading = 25697, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/17/2008").AddMilliseconds(40), FillAmount = 18.004, PricePerUnit = 2.899, OdometerReading = 26080, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/19/2008"), FillAmount = 16.18, PricePerUnit = 3.099, OdometerReading = 26428, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/20/2008"), FillAmount = 15.494, PricePerUnit = 2.999, OdometerReading = 26736, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/21/2008"), FillAmount = 15.077, PricePerUnit = 2.999, OdometerReading = 27029, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/20/2008"), FillAmount = 15.19, PricePerUnit = 2.959, OdometerReading = 27266, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/22/2008"), FillAmount = 16.251, PricePerUnit = 3.075, OdometerReading = 27539, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/17/2008"), FillAmount = 17.556, PricePerUnit = 3.299, OdometerReading = 27856, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/23/2008"), FillAmount = 17.16, PricePerUnit = 3.299, OdometerReading = 28207, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/05/2008"), FillAmount = 15.862, PricePerUnit = 3.339, OdometerReading = 28536, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/17/2008"), FillAmount = 7.199, PricePerUnit = 3.479, OdometerReading = 28680, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/22/2008"), FillAmount = 16.8, PricePerUnit = 3.659, OdometerReading = 29017, OdometerUnit = honda.OdometerUnit, PumpUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/10/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/25/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/19/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/21/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/28/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/28/2008").AddMilliseconds(20), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/03/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/17/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/23/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/23/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/11/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/22/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/12/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/16/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/23/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/29/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/30/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/09/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/17/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/19/2008"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/02/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/04/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/09/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/16/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/23/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/10/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/22/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/25/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/10/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/14/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/18/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/25/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/30/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/11/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/12/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/01/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/17/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/30/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/13/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/15/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/29/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/01/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/07/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/09/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/12/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/19/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/30/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/07/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/08/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/20/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("09/21/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("09/29/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/04/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/04/2009").AddMilliseconds(10), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/16/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/18/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/24/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("10/29/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/05/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/16/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("11/20/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/07/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/23/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/27/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("12/31/2009"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/13/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("01/15/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/09/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("02/23/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/09/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/16/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("03/29/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/04/2010"), PreviousEntryMissed = true, FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/04/2010").AddMilliseconds(20), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/15/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/16/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/22/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("04/28/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/08/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/15/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("05/31/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/15/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/19/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("06/25/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/03/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/03/2010").AddMilliseconds(20), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/03/2010").AddMilliseconds(40), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/21/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/23/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/29/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/31/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("07/31/2010").AddMilliseconds(20), WasNotToppedOff = true, FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/02/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/02/2010").AddMilliseconds(20), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/02/2010").AddMilliseconds(40), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/06/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/07/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/14/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/19/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/21/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            //honda.Entries.Add(new FillupEntry { EntryDate = DateTime.Parse("08/28/2010"), FillAmount = , PricePerUnit = , OdometerDistanceUnit = honda.OdometerDistanceUnit, OdometerReading = , OdometerDistanceUnit = honda.OdometerUnit, PumpVolumeUnit = UnitOfMeasure.Volume.Gallon});
            
            foreach(var entry in honda.Entries)
            {
                entry.PumpUnit = UnitOfMeasure.Volume.Gallon;
            }
            return honda;
        }
    }
}
